### ISSUE TITLE
Image settings do not override default settings

### ISSUE THREAD

**Issue by andrewl913** [peterlazzarino/react-adaptive-image#10]
When configuring of imageResolver function of the initImages function, it seems that imageResolver doesn't bind in time in certain scenarios. 

Possible proposed solution: take an optional image url resolver as a prop in the component that can be eagerly evaluated and re-register dom events. (should only re-register if the resolvedUrl has changed) 

Language: Typescript
Framework: NextJS

**Comment by peterlazzarino** [comment]
Can you post how you set the image resolver and when?

**Comment by peterlazzarino** [comment]
I would like to avoid resolving images on the per image level because of the configuration this would require for each instance.

**Comment by andrewl913** [comment]
I've tried multiple mounting points inside the _document.js  see https://github.com/zeit/next.js#custom-document  and on a page level, (both) are server side rendered.

Another possible solution is maybe wrapping the Root components with a ImageUrlSchemeProvider component or something of the sort

**Comment by peterlazzarino** [comment]
Can you provide a repo i can clone or steps to reproduce so this is actionable and I can see whats going on?

**Comment by peterlazzarino** [comment]
I talked to @andrewl913 and this was determined to be an issue with how the component was being initialized, closing this.
